### ISSUE TITLE
Distinguish attribute value for constant AMR node

### ISSUE THREAD

**Issue by mlciv** [cfmrp/mtool#8] opened 2019-06-10 01:30 UTC
In AMR, constant node values such as string and number are different, however, as follows, in training mrp format, all attribute values are string.  Same issues with the "dot" ouput format. 

<code>
{"id": "20001001",{"id": 2, "label":           ↪"name", "properties": ["op1", "op2"], "values": ["Pierre", "Vinken"]}, {"id": 3, "label": "temporal-quantity", "properties": ["quant"], "values":            ↪["61"]}
<code>

BTW, if possible, can the origin amr string be also added as a field "amr_str" (just as the "input" filed.)  in Graph class when codec amr format.  For that, smatch can work more precisely. Thanks.

**Comment by oepen** [comment] 2019-06-10 08:17
i take your point that the PenMan serialization appears to distinguish string- vs. number-typed constants (in particular when looking at it with the background of a lisp s-expression).

on this view, the MRP serializations have lost this distinction.  on the other hand, our converter to MRP uses the original AMR reader from the SMATCH package, so it also seems clear that this type distinction is not considered relevant for ‘standard’ AMR evaluation.

i suspect SMATCH treating numbers as strings may well be intended to consider 61 and “61” as equivalent, i.e. not penalize for different data types on constants.  we shall make sure to apply the same robustness for evaluation in the MRP context (probably coerce all constants to strings for evaluation).

but why do you think SMATCH could work ‘more precisely’ if the MRP serialization preserved the original AMR string?  part of our motivation in representing all graphs uniformly in MRP is to make sure we (formalize and) capture all relevant information in the abstract representation.  under which circumstances would you expect SMATCH scores to differ if working from PenMan serializations vs. the MRP encoding?

**Comment by mlciv** [comment] 2019-06-12 08:38
Thanks for your replying.  Because I find the scores of smatching with MRP and another smatching with AMR string are different, and then I found the issues in MRP file about string/number distinct.  That's why I deem that 'more precisely' for origin AMR String.   But I am wrong, the problem is not about Penman notation and AMR string, actually it is because of different methods for matching attributes in different versions of smatch scripts, and our AMR to MRP transformer made a mistake on ignoring a special token. 

I found that quoted string actually has been specially treated in AMR Reader by appending a special token '¦': https://github.com/cfmrp/mtool/blob/d4aee602b022a06c2f8138d6463c5de7305918f6/smatch/amr.py#L233

However, when doing match in smatch.py,  '¦' is ignored. That's why smatch in this repo does care. https://github.com/cfmrp/mtool/blob/d4aee602b022a06c2f8138d6463c5de7305918f6/smatch/smatch.py#L239

Previously, I am using a different smatch from https://github.com/ChunchuanLv/amr-evaluation-tool-enhanced/blob/a4284d658365e783a6bb8184db83e08b7cb97d8e/smatch/smatch.py#L229 

What's more, I noticed that our AMR to MRP codec actually also ignored the special token '¦': https://github.com/cfmrp/mtool/blob/d4aee602b022a06c2f8138d6463c5de7305918f6/codec/amr.py#L47 

That's why our mrp format also lose the distinction between quoted string and unquoted value.
To fix it, when we find a label end with '¦',  we should add quotes back instead of ignoring it.

**Comment by oepen** [comment] 2019-06-13 21:04
thanks for the detailed follow-up!  i am afraid i am still not quite sure i understand what exactly you consider problematic?  if there are scoring differences between our MRP wrapper and the official SMATCH, could you provide a test case, ideally the smallest pair of AMRs that exhibit the problem?  for that comparison, could you try the version pointed to from the ISI pages for AMR, which is the following repository:

  [https://github.com/snowblink14/smatch](https://github.com/snowblink14/smatch)

the funny character you discovered ('¦') does indeed reflect a change we made in both the AMR reader ('amr.py') and the comparison ('smatch.py').  the original SMATCH code uses an underscore, i.e. inserts it at the end of a quoted string, and strips it out again when normalizing for comparison.  to not risk doing damage to constants that happen to end in an underscore, we changed the marker to a less common character.  truth be told, i am not sure why the AMR reader inserts this character, but 

but i fail to see how that change should result in divergent scores.  i agree with you that the conversion to MRP loses the type distinction between constants that are quoted strings vs. unquoted number literals.  but it is the 'official' AMR reader that represents both types as constants as Python strings, and i suspect this is actually considered a feature for evaluation, i.e. "42" and 42 shall be considered the same constant (see below).  so, my primary goal in this thread would be to pin-point exactly where you end up with diverging scores, and what is the cause of that discrepancy.

ps: the official test AMRs include the following pair, which appears intended to confirm the robust comparison of different representations of constants:
```
(b / bear-02
      :ARG1 (p / poet :name (n / name :op1 "William" :op2 "Shakespeare"))
      :location (c / city :name (n2 / name :op1 "Stratford-upon-Avon")))
```
```
(b / bear-02
      :ARG1 (p / poet :name (n / name :op1 william :op2 "shakespeare"))
      :location (c / city :name (n2 / name :op1 "Stratford-upon-Avon")))
```

**Comment by mlciv** [comment] 2019-06-14 17:35
Actually, the divergent scores are because of different versions of smatch repo. 
Sorry for the confusion, let me clarify that more clearly. 
I tested with the examples you gave above, the results are as follows:

1. mtool and official smatch. 
Since we follow the official smatch repo https://github.com/snowblink14/smatch, if comparing with the official match,  both our mtool and official smatch will get the same scores: F1-score:  1.00 
I don't know why the official smatch ignoring the difference between quoted and unquoted value. 

2. other smatch extensions. 
But I would say the official smatch has been extended into some other smatch extensions, which are used in more recent AMR papers(such as https://arxiv.org/abs/1805.05286, https://arxiv.org/pdf/1905.08704.pdf). 
https://github.com/mdtux89/amr-evaluation 
or its enhanced version in 
https://github.com/ChunchuanLv/amr-evaluation-tool-enhanced/ 

The above two will get the same F1-score: 0.92

All in all, I think the two smatch extensions are more strict than the official smatch used in mtool.

**Comment by oepen** [comment] 2019-06-14 20:08
warmest thanks for the clarification!  i am glad we now understand the nature of the divergent scores you observed.

we discussed the question of how to compare constants in our weekly conference call today: both MRP co-organizers from the AMR community (bert and tim) confirmed that constant comparison should be robust to variation in quoting conventions and capitalization; in other words, the official SMATCH version does the right thing.

personally, i feel a tad alarmed that there are so many minor variants of the SMATCH code base, and that they can give different scores.  that can make comparison across published results harder than it should be.

i am closing this issue, as for MRP 2019 at least we are inclined to stick to the 'official' SMATCH code, i.e. the repository linked from the ISI pages.  but do feel free to re-open, in case you turn up more questions in this space!

**Comment by mlciv** [comment] 2019-06-18 01:13
Thanks. When I explored this again for evaluting with my generated MRP with gold MRP.  I think there is still one bug about quoted attribute when smatching two mrp file.  
                                                                                                                                                                                                         
As I mentioned previously, the official smatch use a "normaliz" function to normalize attributes by deleting the "¦" and lower the case. (which is based amr reader in official smatch) https://github.com/cfmrp/mtool/blob/e97bb506c47f6ef774a0de6680b3dacd212302d0/smatch/smatch.py#L183

In MRP 2019, if we strictly follow the amr guidelines, we should output a quoted value as an attribute in mrp. Such as :  
`{'id': 2, 'label': 'name',  'properties': ['op1', 'op2'], 'values': ['\"Pierre\"', '\"Vinken\"']}` 

Given this, the above "normalize" funtion will fail because it still try to delete "¦" for normalizing, while the "\"" instead of "¦" will be natually used as quoting when predicting. 
Otherwise, it means in MRP 2019, we had better not to predict any quoted string in mrp format. 

Also, in my opinion, we suggested that the quoted attributes should be kept in our training dataset to strictly follow the AMR guidelines. Please consider this. Thanks.

**Comment by oepen** [comment] 2019-06-18 20:42
i feel we work from different assumptions about how constants in AMR should be interpreted.  when you refer to the AMR guidelines, what exactly do you have in mind?  so far, i have been unable to turn up any discussion of different types of constants, so for all i know, the following are all equivalent ways of writing the same constant in PenMan notation: `Pierre`, `pierre`, `"Pierre"`, or `"pierre"`.  in other words, the double quotes in native AMR files are not part of the constant itself but rather part of one of the PenMan ways of writing down constants.  in python, all constants (including numbers) are represented as strings, so the above will always: `"values": ["Pierre"]`.  this constant has a length of six character.  thus, i must recommend against you putting double quotes inside your constants, i.e. something like `"values": ["\"Pierre\""]`.  that would be a JSON string representing a different constant, viz. one whose first and last character is a double quote, and whose total length is eight characters.  note that JSON strings (unlike Python) strings must use double quotes, not single quotes.

the funny `¦` symbol you noticed in our variant of the SMATCH code is a red herring, i think.  it is unrelated to the question of how to represent and interpret constants.

@timjogorman: does the above sound right to you?

**Comment by mlciv** [comment] 2019-06-19 23:07
From my understaning of AMR( in penman notation), there are 3 kinds of constant node.
1.  String Value (quoted)
For example,  the name "Pierre" or the book name "1984", simple string value  "a" in sentence `'a' is 
a common word in english`
2. Numeric Value (unquoted)
For example, all the numeric values
3. Special Named Constant (unquoted)
For example, +, -, expressive, imperative

In mrp, all of them are unquoted but in `string type` in python or json, in that way, any unquoted AMR string value will share the same value with numbers and special named constant are not easy to read, such as a string value "expressive" vs named special constant `expressive` , string "61"  and `61`.

That's why I also suggest to use quoted string for AMR string in mrp as that in penman notation.

**Comment by timjogorman** [comment] 2019-06-20 20:15
I'd agree that the PENMAN format technically distinguishes between strings, numbers, and constants, but it's worth emphasizing that this has never been a semantically important distinction where human annotators are providing the information: it's purely a convention of the PENMAN format itself.  Moreover, I'm pretty sure that the subtypes of "constant" nodes can be deterministically recovered (this distinction was deterministically implemented by the annotation tool during AMR creation anyway). 

We debated whether to capture this distinction, but even if we did, it would have made more sense to have people predict the type (string, numeric value, special constant) on the node property, rather than storing the quotation marks  -- AMR is not actually asserting that Pierre Vinken's name has quotation marks in it, the quotation marks are just how the PENMAN notation was storing that string.  More importantly, storing names directly helps to make AMR representations of constants more similar to how other semantic graphs are capturing the same elements, which I assume might be helpful if people are trying to do any multi-task learning. 

Ideally, I'd like to set up a converter from MRP to PENMAN, and that would naturally need to enact this formatting difference, but for the evaluation we're following the official smatch implementation in not being picky about this particular distinction.

**Comment by mlciv** [comment] 2019-06-21 00:10
Thanks for the clarification. I agree that the distinction of constant type is not that semantically important,  and they can be recovered determistically from MRP.  There is no problem if MRP decide not to distinguish them excplicitly.

Let me make a summary here for future reference:

1. Three subtypes of constant: qutoted strings, numbers, and constants are purely convention in PENMAN notation of AMR. 
2. MRP will not use extra quotes to explicitly distinguish those subtypes. 
(P.S. If necessary for using the subtypes(e.g. using previous AMR model based on PENMAN), we can do the recovering after reading MRP, and use that internally in our parsing model. )
3. When predicting the AMR in MRP, we should not use the quotation marks for strings. 

(However, the current smatch used in "mtool" is "picky" for the distinction, because node.normalize() doesn't normalize quoted string properities(if predicted) in MRP before comparing. This is the remaining issue for this thread. Thanks.)

**Comment by oepen** [comment] 2019-06-24 11:27
> (However, the current smatch used in "mtool" is "picky" for the distinction, because node.normalize() doesn't normalize quoted string properities(if predicted) in MRP before comparing. This is the remaining issue for this thread. Thanks.)

in the above comment, are you thinking we might want to be even more robust in comparing constants and consider the JSON strings "Pierre" and "\"Pierre\"" equivalent?  personally, i feel a tad skeptical of this move, in part because the MRP training data never provides a string like "\"Pierre\"" (which, technically, would be a constant eight characters in length), in part because on our view of AMR constants and PenMan conventions, the outermost pair of (unescaped) double quotes are not part of the value but merely part of (one of the different ways in) the PenMan syntax for writing down the constant `Pierre`.

on the other hand, added robustness can hardly be a problem, so i am leaving this issue open for now to see what my co-organizers think of the suggestion?

**Closed** 2019-06-24 20:14 UTC
